version: "3.8"

services:
  simple-ml:
    platform: linux/amd64
    build:
      context: ./build
      tags:
        - "simple-ml:${IMAGE_TAG:-latest}"
        
    image: simple-ml:${IMAGE_TAG:-latest}
    
    ## For Nvidia GPU's - You probably want to uncomment this
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    devices:
      - "/dev/dri:/dev/dri"
      ## For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      
    volumes:
      ## Workspace
      - ./workspace:/workspace:rshared
      
    ports:
        # Jupyter Lab
        - ${JUPYTER_PORT_HOST:-8888}:8888
        # TensorBoard
        - ${TENSORBOARD_PORT_HOST:-6006}:6006
        # File Browser
        - ${FILEBROWSER_PORT_HOST:-8080}:8080
        # Infinite Browser
        - ${INFINITE_BROWSER_PORT_HOST:-8188}:8188
   
    environment:
        # Don't enclose values in quotes
        - WORKSPACE=/workspace
        - JUPYTER_PORT_HOST=${JUPYTER_PORT_HOST:-8888}
        - TENSORBOARD_PORT_HOST=${TENSORBOARD_PORT_HOST:-6006}
        - FILEBROWSER_PORT_HOST=${FILEBROWSER_PORT_HOST:-8080}
        - INFINITE_BROWSER_PORT_HOST=${INFINITE_BROWSER_PORT_HOST:-8188}
        - TENSORBOARD_LOG_DIR=${TENSORBOARD_LOG_DIR:-/workspace/logs}
        # CUDA環境変数
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
